version: '3'
services:
  codeceptjs:
    image: codeception/codeceptjs
    depends_on:
      - chrome
    volumes:
      - .:/tests

  chrome:
    container_name: selenium
    image: selenium/standalone-chrome:3.13.0-argon
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - '4444:4444'
